plugins {
	id 'application'
	id 'com.gradleup.shadow' version '9.4.1'
	id 'com.google.protobuf' version '0.10.0'
}

repositories {
	maven {
		url = 'https://oss.sonatype.org/content/repositories/snapshots/'
	}

	flatDir { dirs 'libs' }
}

project.version = '1.14.1'

dependencies {
	implementation project(':G3Utils'), project(':LrentNode'), project(':NavMap')
	implementation 'com.formdev:jide-oss:3.7.15'
	implementation 'org.swinglabs.swingx:swingx-all:1.6.5-1'
	implementation 'com.jgoodies:jgoodies-looks:2.7.0'
	implementation 'com.glazedlists:glazedlists:1.11.0'
	// MUST NOT be upgraded, breaks Java 1.8 compatibility.
	implementation 'ch.qos.logback:logback-classic:1.3.4'
	implementation 'org.slf4j:jul-to-slf4j:2.0.18'
	implementation 'uk.org.lidalia:sysout-over-slf4j-context:2.0.0-SNAPSHOT'
	implementation 'uk.org.lidalia:sysout-over-slf4j-system:2.0.0-SNAPSHOT'
	// Transitive dependencies of sysout-over-slf4j
	implementation 'uk.org.lidalia:lidalia-slf4j-ext:1.0.0'
	implementation 'uk.org.lidalia:lidalia-lang:1.0.0'
	implementation 'org.jmonkeyengine:jme3-core:3.5.2-stable'
	implementation 'org.jmonkeyengine:jme3-desktop:3.5.2-stable'
	implementation 'org.jmonkeyengine:jme3-lwjgl3:3.5.2-stable'
	implementation 'io.github.classgraph:classgraph:4.8.184'
	implementation 'org.zeromq:jeromq:0.6.0'
	implementation 'com.google.protobuf:protobuf-java:2.6.1'
	implementation 'net.jodah:expiringmap:0.5.11'
	implementation 'com.github.tulskiy:jkeymaster:1.3-CUSTOM'
	// Transitive dependencies of jkeymaster
	implementation 'net.java.dev.jna:jna:5.18.1'
	implementation 'net.java.dev.jna:jna-platform:5.18.1'
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.21.3'
	implementation 'com.fasterxml.jackson.module:jackson-module-parameter-names:2.21.3'
	implementation 'com.j2html:j2html:1.6.0'
	implementation 'hu.kazocsaba:image-viewer:1.2.5-g3dit'
	implementation 'org.apache.commons:commons-csv:1.14.1'
	implementation 'net.sf.cssbox:cssbox:4.17'
	implementation 'net.sf.cssbox:swingbox:1.2-SNAPSHOT'
	implementation 'commons-io:commons-io:2.22.0' // Used by net.sf.cssbox.swingbox
	implementation 'ca.phon.ui:jbreadcrumb:4'
	implementation 'net.sourceforge.argparse4j:argparse4j:0.9.0'
	implementation 'com.formdev:flatlaf:3.7.1'
	implementation 'com.formdev:flatlaf-intellij-themes:3.7.1'
	implementation 'com.formdev:flatlaf-extras:3.7.1'
	implementation 'com.formdev:flatlaf-swingx:3.7.1'
	implementation 'com.formdev:flatlaf-jide-oss:3.7.1'
	implementation 'com.l2fprod.common:l2fprod-common-shared:10.0'
	implementation 'com.l2fprod.common:l2fprod-common-sheet:10.0'
	testImplementation 'junit:junit:4.13.2'
}

protobuf {
	// Configure the protoc executable
	protoc {
		// Download from repositories
		artifact = 'com.google.protobuf:protoc:2.6.1'
	}
}

jar {
	manifest {
		attributes(
				'Class-Path': 'config/',
				'Main-Class': 'de.george.g3dit.Editor',
				'g3dit-Version': project.version
		)
	}
	processResources {
		exclude('logback-test.xml')
	}
}

application {
	mainClass = 'de.george.g3dit.Editor'
	applicationDefaultJvmArgs = ['-XX:+IgnoreUnrecognizedVMOptions', '-XX:+UseG1GC',
								 '-XX:MinHeapFreeRatio=5', '-XX:MaxHeapFreeRatio=20',
								 '--add-opens=java.desktop/java.awt=ALL-UNNAMED',
								 '--add-opens=java.desktop/javax.swing=ALL-UNNAMED',
								 '--add-opens=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED',
								 '--add-opens=java.base/sun.nio.fs=ALL-UNNAMED',
								 '--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED',
								 '-Djava.library.path=".;libs"']
}

tasks.run {
	workingDir = "$projectDir/root"
}

tasks.compileJava {
	dependsOn(project.parent.tasks.generateGettextSources)
}

tasks.shadowJar {
	duplicatesStrategy = DuplicatesStrategy.INCLUDE
	mergeServiceFiles()
	transform(com.github.jengelman.gradle.plugins.shadow.transformers.ApacheLicenseResourceTransformer)
	transform(com.github.jengelman.gradle.plugins.shadow.transformers.ApacheNoticeResourceTransformer)
	transform(com.github.jengelman.gradle.plugins.shadow.transformers.PreserveFirstFoundResourceTransformer) {
		include 'META-INF/AL2.0'
		include 'META-INF/LGPL2.1'
	}
  	failOnDuplicateEntries = true
}

task copyBinlib(type: Copy) {
	dependsOn 'shadowJar'
	from("$projectDir/libs") {
		include "xfiledialog*.dll"
	}
	into "$projectDir/root/libs"
}

task copyJar(type: Copy) {
	dependsOn 'copyBinlib'
	from layout.buildDirectory.file("libs/${project.name}-${project.version}-all.jar")
	into "$projectDir/root/"
	rename ".*", "${project.name}.jar"
}

task dist(type: Zip) {
	dependsOn 'copyJar'
	into ('') {
		from 'root/' + project.name + '.exe'
		from 'root/' + project.name + 'c.exe'
		from 'root/' + project.name + '.bat'
		from 'root/' + project.name + 'c.bat'
		from 'root/' + project.name + '.sh'
		from 'root/' + project.name + 'c.sh'
		from 'root/' + project.name + '.jar'
		filePermissions {unix("rwxr-xr-x") }
	}
	into('libs') {
		from 'root/libs'
	}
	into('config') {
		from 'root/config'
		exclude 'g3dit*.json*'
	}
	destinationDirectory = file('dist')
	archiveFileName = project.name + '_' + project.version.replace(' ', '_') + ".zip"
}

task prefixNewMigrations {
	fileTree(dir: 'src/main', includes: ['java/de/george/g3dit/settings/migrations/*.java']).exclude({ isFilePrefixed(it.file) }).each { file ->
		doLast {
			def timestamp = new Date().format('yyyyMMddHHmmssSSS', TimeZone.getTimeZone('CET'))

			println "Renaming $file.name to ${timestamp}__$file.name"

			file.renameTo("${file.parentFile.absolutePath}${file.separator}V${timestamp}__${file.name}")

			// Sleep for a moment to avoid prefix conflicts when renaming multiple files
			sleep(1 * 1000)
		}
	}
}

def isFilePrefixed(file) {
	return (file.name ==~ '^V\\d+__.*\\.java\$')
}
